### ISSUE TITLE
failed attempted to upload file after sending bch transaction

### ISSUE THREAD

**Issue by lawsoncreativeworks** [DesWurstes/BlockUpload#1]
Hi DesWurstes, 
Thanks for creating this valuable innovation, I'm very excited to use, help test, and promote. 

Unfortunately I made an attempt to upload a file, the browser seemed to get stuck or crash, though the transaction was completed, and there was no way to submit a support ticket. 

Would you mind refunding the bch transaction: 

7/28 transaction, to upload file pgw-2-17.txt
You just sent 0.0489 BCH to 1YgWaHPWzc1Dyww9RTR5k8uozU55H4As7
https://explorer.bitcoin.com/bch/address/1YgWaHPWzc1Dyww9RTR5k8uozU55H4As7

Please advise, thanks so much, I look forward to seeing this project grow and using it often for proof of existence / notary use cases. 

Best regards,
-Ben

**Comment by DesWurstes** [comment]
Hi,

It is usual for it to seem stuck for up to twenty minutes, since it waits for the a block. Depending on the file size, it might take up to 50 minutes. If you suspect that an error caused it to stop, you should open Inspect > Console and post the output here (if one of the last few lines isn't red, everything should be fine.)

I'll look for a way for you to take back most of your Bitcoin Cash and I'll let you know.

**Comment by lawsoncreativeworks** [comment]
ah thanks for the update, unfortunately I don't have a way to inspect that attempt, I will be sure to follow your instructions to inspect next time I make an attempt. 

Please let me know if any further info is needed for a partial refund of bch, thanks! I appreciate the response and will continue to use and promote the service as the bugs get worked out, best regards!

**Comment by DesWurstes** [comment]
Hi,

Was the address Blockupload io generated and asked you to send coins this: bitcoincash:qqzlmczzw9udkztqdlwalrawrak43wzkhc0lwneqam ?

Could you please confirm that you didn't press "Start Uploading" after the browser was stuck (either with the same file or a different file)? Then, you should open Blockupload.io, and enter

```
localStorage.getItem("current_upload")
```
to the JS console. This will be the private key generated when you pressed "Start Uploading" for the last time, you should note this somewhere. If you pressed "Start Uploading" after the browser was stuck, then unfortunately recovering the coins isn't possible.

Once you answer the first question (Was the address...) I'll modify the code I linked below. Here's the summary of what I'll suggest you to do after that:

Then you can download and run [this version](https://github.com/DesWurstes/BlockUpload/archive/reco.zip) which'll try to generate the exact transactions but won't push them. You can then share the console output here. Then it should be possible to recover the coins.

**Comment by lawsoncreativeworks** [comment]
Hi,
Yes that is the correct bch address that I sent payment to here's the block explorer: 
https://explorer.bitcoin.com/bch/address/1YgWaHPWzc1Dyww9RTR5k8uozU55H4As7

Unfortunately I've reformatted the computer I used for this transaction a few months ago. I'm wondering if your server has any record of this attempt because I can attest the file uploaded is named: pgw-2-17.txt

I'll try testing again with a smaller text string soon and be sure to follow your instructions and take screen shots where appropriate. 

Thanks

**Comment by lawsoncreativeworks** [comment]
i was able to complete the upload process, received change, then go to this page but i get a "not found" error message: 

https://blockupload.io/download.html#txid=0bded37548ad2bafe88f057f7398957aafe02842e7b62610dc27e3078cee7f40

but there is something on chain here: 
https://explorer.bitcoin.com/bch/tx/0bded37548ad2bafe88f057f7398957aafe02842e7b62610dc27e3078cee7f40

**Comment by DesWurstes** [comment]
Thanks for the bug report, I've fixed the "not found" error in [this commit](https://github.com/DesWurstes/BlockUpload/commit/e12c2d2e332f20b9648e60b88dbb58e944788aca), and it's now accessible at BlockUpload.io.

> Unfortunately I've reformatted the computer I used for this transaction a few months ago. I'm wondering if your server has any record of this attempt because I can attest the file uploaded is named: pgw-2-17.txt

[bch.coin.space](bch.coin.space)'s API is used to push transactions, but unless the private key was recorded before attempting to upload a different file, it's impossible to recover the coins, I'm really sorry about this.

**Comment by lawsoncreativeworks** [comment]
great! I was able to download the file, yay! 

what i did differently this time is wait and refresh the blockexplorer until multiple confirmations before clicking the "start uploading button", perhaps you'll want to put some help text there or a notification too wait for network confirmations before closing the windows, giving up, etc. or have some kind of graphic of a spinning wheel or clock to indicate that a pending transaction verification is happening in the background. I'm not sure what you'll decide is the best way to update the user experience, but that would be helpful. 

As far as the original lost transaction, that's for the apology, I guess if you can't access the recipient address account then it's a lost cause. I should have tested with a smaller amount, so I'll consider it a hard lesson learned, but I'm glad I followed up because I really want to use this service regularly and if it continues to be supported and enhanced, I hope it's a good source of income, I can see this having much more value than the simple notarization of a file hash, with this service, you can truly immortalize small vital records, documents, etc. 

thanks!

**Comment by lawsoncreativeworks** [comment]
correction "thanks for the apology" :)

**Comment by lawsoncreativeworks** [comment]
one question, is there a way to manually retrieval the file from the block chain if for any reason blockupload.io is down or is discontinued?

**Comment by DesWurstes** [comment]
> perhaps you'll want to put some help text there or a notification too wait for network confirmations before closing the windows, giving up, etc.

I've put this on my TODO list, thanks for the idea. In addition a backup file containing private keys, transactions, and maybe replacement transactions that can be published as a way to cancel the file upload and refund the coins. Most importantly, it should show that it'll take some time.

> one question, is there a way to manually retrieval the file from the block chain if for any reason blockupload.io is down or is discontinued?

You can find the production code with minified (unreadable) code [here](https://github.com/DesWurstes/BlockUpload/tree/gh-pages), with the development code (requires `util.js` and `util.wasm` generated by `wasm.command`) [here](https://github.com/DesWurstes/BlockUpload/tree/frontend). All scripts and wasm-generating code is [here](https://github.com/DesWurstes/BlockUpload/tree/master). If you only want to use it, you should click the first link, choose "clone or download" and then "Download ZIP". That should work as long as bch.coin.space works.

**Comment by lawsoncreativeworks** [comment]
ok great thanks!
