### ISSUE TITLE
Change not able to be sent after file upload

### ISSUE THREAD

**Issue by jowesco** [DesWurstes/BlockUpload#2]
Hello,

I am fascinated by the concept of storing files permanently on an immutable decentralized ledger.  It boggles the mind.

Anyway I just wanted to try it out, I think the file uploaded based on the series of TXIDs from the output I sent to.  But there is about $3 usd worth of change that I can't seem to get sent back to me, 

I sent 0.0125 BCH to this address on blockupload.io
bitcoincash:qrlg8g0xfz3rql357qvqarhrez7s39tg7unge833mt

I tried to have the change of 0.00699500 BCH sent back to me here
bitcoincash:qzx448yucq0ypkhqygzja4gzxalpffxeyvunak766d

At fiirst I was getting PushTX error 6, then this:
Pushtx error: 0
Internal Server Error

Not a big deal just hoping you can help me out.
Thanks!

**Comment by DesWurstes** [comment]
Hi,

Could you please open blockupload.io, not press any button, but do Inspect Element > Storage > Local Storage

and paste the values of `current_upload` and `first_utxo` here.

But for me to manually solve this, I need the file as well, unless it's encrypted.

Thank you

**Comment by jowesco** [comment]
Thank you for responding!

Yes -
current_upload
L56yjXi6xv1ZnDY9S8qRCUNjM6f72e9ad2waohVWMeQnmo2QYXks

first_utxo

   1. [{address: "1QCkKhwMygjxKA1RA7TBcoNJ5ktooXLGxa",…}]
      1. 0: {address: "1QCkKhwMygjxKA1RA7TBcoNJ5ktooXLGxa",…}
         1. address: "1QCkKhwMygjxKA1RA7TBcoNJ5ktooXLGxa"
         2. confirmations: 0
         3. satoshis: 1250000
         4. txid: "
         fd4c697ad2d48851e2cce4549c37e4d51c16e3965f5e1c45b4595de2e5bf6a6f"
         5. vout: 0

**Comment by DesWurstes** [comment]
I have updated the code so that if this occurs again it will continue attempting to push the transaction. It was caused by a random Internal Server Error. I have also updated the file downloading tab, it doesn't currently work. I will deploy these changes in a week.

Thanks,
Blockupload.io developer

**Comment by jowesco** [comment]
Thank you sir, You are doing important work here - this could potentially bring un-censorable content to a lot of people!  Also thanks for the help!

**Comment by DesWurstes** [comment]
Thank you for your kind words!

I have deployed the changes.
